# Generated by Django 5.2.2 on 2025-07-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bestPerfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=300)),
                ('sector', models.CharField(max_length=100)),
                ('fin_yahoo_screen_path', models.CharField(max_length=500)),
            ],
        ),
    ]
