# Generated by Django 5.2.2 on 2025-07-12 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestperf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestperf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=300)),
                ('fin_yahoo_screen_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='bestPerfs',
        ),
        migrations.AddField(
            model_name='bestperf',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_perfs', to='bestperf.sector'),
        ),
    ]
