# Generated by Django 5.2.2 on 2025-07-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestperf', '0002_bestperf_sector_delete_bestperfs_bestperf_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestperf',
            name='fin_yahoo_screen_path',
            field=models.CharField(default='', max_length=500),
        ),
    ]
