# Generated by Django 5.2.2 on 2025-07-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestperf', '0003_alter_bestperf_fin_yahoo_screen_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestperf',
            name='fin_yahoo_screen_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
