# Generated by Django 5.2.2 on 2025-07-13 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestperf', '0004_alter_bestperf_fin_yahoo_screen_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestperf',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bestperf',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_perfs', to='bestperf.sector'),
        ),
    ]
