# Generated by Django 5.2.2 on 2025-07-17 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestperf', '0005_alter_bestperf_name_alter_bestperf_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_yahoo_screen_path', models.CharField(blank=True, max_length=500, null=True)),
                ('fin_google_screen_path', models.CharField(blank=True, max_length=500, null=True)),
                ('finchart_google_screen_path', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='bestperf',
            name='fin_yahoo_screen_path',
        ),
        migrations.AddField(
            model_name='bestperf',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bestperf',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bestperf',
            name='screens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_perfs', to='bestperf.screens'),
        ),
        migrations.AddField(
            model_name='bestperf',
            name='stock_exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_perfs', to='bestperf.stockexchange'),
        ),
    ]
