# Generated by Django 5.2.2 on 2025-07-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestperf', '0006_screens_stockexchange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestperf',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
