# Generated by Django 5.2.2 on 2025-07-21 10:45

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bestperf', '0007_alter_bestperf_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WatchComp',
            fields=[
                ('bestperf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bestperf.bestperf')),
                ('relation_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_list', to='bestperf.relationtouser')),
            ],
            bases=('bestperf.bestperf',),
        ),
    ]
