# Generated by Django 5.2.2 on 2025-07-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestperf', '0008_relationtouser_watchcomp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchComp',
        ),
    ]
