# Generated by Django 5.2.2 on 2025-07-22 18:53

import django.db.models.deletion
from django.db import migrations, models

def insert_default_relation_to_user(apps, schema_editor):
    RelationToUser = apps.get_model('bestperf', 'RelationToUser')
    RelationToUser.objects.bulk_create([
        RelationToUser(title='Own'),
        RelationToUser(title='Watch'),
    ])
class Migration(migrations.Migration):

    dependencies = [
        ('bestperf', '0009_delete_watchcomp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('relation_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_list', to='bestperf.relationtouser')),
                ('screens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_list', to='bestperf.screens')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_list', to='bestperf.sector')),
                ('stock_exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_list', to='bestperf.stockexchange')),
            ],
        ),
        migrations.RunPython(insert_default_relation_to_user),
    ]
