# Generated by Django 5.2.2 on 2025-07-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestperf', '0010_watchcompanies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchcompanies',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
