# Generated by Django 5.2.2 on 2025-07-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestperf', '0011_alter_watchcompanies_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchcompanies',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
